/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoIndexRouteImport } from './routes/demo/index'
import { Route as DemoAdditionGrokkingRouteImport } from './routes/demo/addition-grokking'
import { Route as DemoDamTestRouteImport } from './routes/demo/dam-test'
import { Route as DemoDenseAssociativeMemoryRouteImport } from './routes/demo/dense-associative-memory'
import { Route as DemoLinearSystemsRouteImport } from './routes/demo/linear-systems'
import { Route as DemoMnistNkClusteringRouteImport } from './routes/demo/mnist-nk-clustering'
import { Route as DemoMnistTrainingRouteImport } from './routes/demo/mnist-training'
import { Route as DemoNeedleRouteImport } from './routes/demo/needle'
import { Route as DemoNkClusteringRouteImport } from './routes/demo/nk-clustering'
import { Route as DemoOnlineKMeansRouteImport } from './routes/demo/online-k-means'
import { Route as DemoRivalKRouteImport } from './routes/demo/rival-k'
import { Route as DemoSheafAdmmMnistRouteImport } from './routes/demo/sheaf-admm-mnist'
import { Route as DemoTwoMoonRouteImport } from './routes/demo/two-moon'
import { Route as DemosIndexRouteImport } from './routes/demos/index'
import { Route as DemosSlugRouteImport } from './routes/demos/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/demo/',
  path: '/demo/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoAdditionGrokkingRoute = DemoAdditionGrokkingRouteImport.update({
  id: '/demo/addition-grokking',
  path: '/demo/addition-grokking',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDamTestRoute = DemoDamTestRouteImport.update({
  id: '/demo/dam-test',
  path: '/demo/dam-test',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDenseAssociativeMemoryRoute =
  DemoDenseAssociativeMemoryRouteImport.update({
    id: '/demo/dense-associative-memory',
    path: '/demo/dense-associative-memory',
    getParentRoute: () => rootRouteImport,
  } as any)
const DemoLinearSystemsRoute = DemoLinearSystemsRouteImport.update({
  id: '/demo/linear-systems',
  path: '/demo/linear-systems',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoMnistNkClusteringRoute = DemoMnistNkClusteringRouteImport.update({
  id: '/demo/mnist-nk-clustering',
  path: '/demo/mnist-nk-clustering',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoMnistTrainingRoute = DemoMnistTrainingRouteImport.update({
  id: '/demo/mnist-training',
  path: '/demo/mnist-training',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoNeedleRoute = DemoNeedleRouteImport.update({
  id: '/demo/needle',
  path: '/demo/needle',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoNkClusteringRoute = DemoNkClusteringRouteImport.update({
  id: '/demo/nk-clustering',
  path: '/demo/nk-clustering',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoOnlineKMeansRoute = DemoOnlineKMeansRouteImport.update({
  id: '/demo/online-k-means',
  path: '/demo/online-k-means',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRivalKRoute = DemoRivalKRouteImport.update({
  id: '/demo/rival-k',
  path: '/demo/rival-k',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoSheafAdmmMnistRoute = DemoSheafAdmmMnistRouteImport.update({
  id: '/demo/sheaf-admm-mnist',
  path: '/demo/sheaf-admm-mnist',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTwoMoonRoute = DemoTwoMoonRouteImport.update({
  id: '/demo/two-moon',
  path: '/demo/two-moon',
  getParentRoute: () => rootRouteImport,
} as any)
const DemosIndexRoute = DemosIndexRouteImport.update({
  id: '/demos/',
  path: '/demos/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemosSlugRoute = DemosSlugRouteImport.update({
  id: '/demos/$slug',
  path: '/demos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo/addition-grokking': typeof DemoAdditionGrokkingRoute
  '/demo/dam-test': typeof DemoDamTestRoute
  '/demo/dense-associative-memory': typeof DemoDenseAssociativeMemoryRoute
  '/demo/linear-systems': typeof DemoLinearSystemsRoute
  '/demo/mnist-nk-clustering': typeof DemoMnistNkClusteringRoute
  '/demo/mnist-training': typeof DemoMnistTrainingRoute
  '/demo/needle': typeof DemoNeedleRoute
  '/demo/nk-clustering': typeof DemoNkClusteringRoute
  '/demo/online-k-means': typeof DemoOnlineKMeansRoute
  '/demo/rival-k': typeof DemoRivalKRoute
  '/demo/sheaf-admm-mnist': typeof DemoSheafAdmmMnistRoute
  '/demo/two-moon': typeof DemoTwoMoonRoute
  '/demos/$slug': typeof DemosSlugRoute
  '/demo/': typeof DemoIndexRoute
  '/demos/': typeof DemosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/addition-grokking': typeof DemoAdditionGrokkingRoute
  '/demo/dam-test': typeof DemoDamTestRoute
  '/demo/dense-associative-memory': typeof DemoDenseAssociativeMemoryRoute
  '/demo/linear-systems': typeof DemoLinearSystemsRoute
  '/demo/mnist-nk-clustering': typeof DemoMnistNkClusteringRoute
  '/demo/mnist-training': typeof DemoMnistTrainingRoute
  '/demo/needle': typeof DemoNeedleRoute
  '/demo/nk-clustering': typeof DemoNkClusteringRoute
  '/demo/online-k-means': typeof DemoOnlineKMeansRoute
  '/demo/rival-k': typeof DemoRivalKRoute
  '/demo/sheaf-admm-mnist': typeof DemoSheafAdmmMnistRoute
  '/demo/two-moon': typeof DemoTwoMoonRoute
  '/demos/$slug': typeof DemosSlugRoute
  '/demo': typeof DemoIndexRoute
  '/demos': typeof DemosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo/addition-grokking': typeof DemoAdditionGrokkingRoute
  '/demo/dam-test': typeof DemoDamTestRoute
  '/demo/dense-associative-memory': typeof DemoDenseAssociativeMemoryRoute
  '/demo/linear-systems': typeof DemoLinearSystemsRoute
  '/demo/mnist-nk-clustering': typeof DemoMnistNkClusteringRoute
  '/demo/mnist-training': typeof DemoMnistTrainingRoute
  '/demo/needle': typeof DemoNeedleRoute
  '/demo/nk-clustering': typeof DemoNkClusteringRoute
  '/demo/online-k-means': typeof DemoOnlineKMeansRoute
  '/demo/rival-k': typeof DemoRivalKRoute
  '/demo/sheaf-admm-mnist': typeof DemoSheafAdmmMnistRoute
  '/demo/two-moon': typeof DemoTwoMoonRoute
  '/demos/$slug': typeof DemosSlugRoute
  '/demo/': typeof DemoIndexRoute
  '/demos/': typeof DemosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo/addition-grokking'
    | '/demo/dam-test'
    | '/demo/dense-associative-memory'
    | '/demo/linear-systems'
    | '/demo/mnist-nk-clustering'
    | '/demo/mnist-training'
    | '/demo/needle'
    | '/demo/nk-clustering'
    | '/demo/online-k-means'
    | '/demo/rival-k'
    | '/demo/sheaf-admm-mnist'
    | '/demo/two-moon'
    | '/demos/$slug'
    | '/demo/'
    | '/demos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo/addition-grokking'
    | '/demo/dam-test'
    | '/demo/dense-associative-memory'
    | '/demo/linear-systems'
    | '/demo/mnist-nk-clustering'
    | '/demo/mnist-training'
    | '/demo/needle'
    | '/demo/nk-clustering'
    | '/demo/online-k-means'
    | '/demo/rival-k'
    | '/demo/sheaf-admm-mnist'
    | '/demo/two-moon'
    | '/demos/$slug'
    | '/demo'
    | '/demos'
  id:
    | '__root__'
    | '/'
    | '/demo/addition-grokking'
    | '/demo/dam-test'
    | '/demo/dense-associative-memory'
    | '/demo/linear-systems'
    | '/demo/mnist-nk-clustering'
    | '/demo/mnist-training'
    | '/demo/needle'
    | '/demo/nk-clustering'
    | '/demo/online-k-means'
    | '/demo/rival-k'
    | '/demo/sheaf-admm-mnist'
    | '/demo/two-moon'
    | '/demos/$slug'
    | '/demo/'
    | '/demos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoAdditionGrokkingRoute: typeof DemoAdditionGrokkingRoute
  DemoDamTestRoute: typeof DemoDamTestRoute
  DemoDenseAssociativeMemoryRoute: typeof DemoDenseAssociativeMemoryRoute
  DemoLinearSystemsRoute: typeof DemoLinearSystemsRoute
  DemoMnistNkClusteringRoute: typeof DemoMnistNkClusteringRoute
  DemoMnistTrainingRoute: typeof DemoMnistTrainingRoute
  DemoNeedleRoute: typeof DemoNeedleRoute
  DemoNkClusteringRoute: typeof DemoNkClusteringRoute
  DemoOnlineKMeansRoute: typeof DemoOnlineKMeansRoute
  DemoRivalKRoute: typeof DemoRivalKRoute
  DemoSheafAdmmMnistRoute: typeof DemoSheafAdmmMnistRoute
  DemoTwoMoonRoute: typeof DemoTwoMoonRoute
  DemosSlugRoute: typeof DemosSlugRoute
  DemoIndexRoute: typeof DemoIndexRoute
  DemosIndexRoute: typeof DemosIndexRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/demo'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/addition-grokking': {
      id: '/demo/addition-grokking'
      path: '/demo/addition-grokking'
      fullPath: '/demo/addition-grokking'
      preLoaderRoute: typeof DemoAdditionGrokkingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/dam-test': {
      id: '/demo/dam-test'
      path: '/demo/dam-test'
      fullPath: '/demo/dam-test'
      preLoaderRoute: typeof DemoDamTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/dense-associative-memory': {
      id: '/demo/dense-associative-memory'
      path: '/demo/dense-associative-memory'
      fullPath: '/demo/dense-associative-memory'
      preLoaderRoute: typeof DemoDenseAssociativeMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/linear-systems': {
      id: '/demo/linear-systems'
      path: '/demo/linear-systems'
      fullPath: '/demo/linear-systems'
      preLoaderRoute: typeof DemoLinearSystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/mnist-nk-clustering': {
      id: '/demo/mnist-nk-clustering'
      path: '/demo/mnist-nk-clustering'
      fullPath: '/demo/mnist-nk-clustering'
      preLoaderRoute: typeof DemoMnistNkClusteringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/mnist-training': {
      id: '/demo/mnist-training'
      path: '/demo/mnist-training'
      fullPath: '/demo/mnist-training'
      preLoaderRoute: typeof DemoMnistTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/needle': {
      id: '/demo/needle'
      path: '/demo/needle'
      fullPath: '/demo/needle'
      preLoaderRoute: typeof DemoNeedleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/nk-clustering': {
      id: '/demo/nk-clustering'
      path: '/demo/nk-clustering'
      fullPath: '/demo/nk-clustering'
      preLoaderRoute: typeof DemoNkClusteringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/online-k-means': {
      id: '/demo/online-k-means'
      path: '/demo/online-k-means'
      fullPath: '/demo/online-k-means'
      preLoaderRoute: typeof DemoOnlineKMeansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/rival-k': {
      id: '/demo/rival-k'
      path: '/demo/rival-k'
      fullPath: '/demo/rival-k'
      preLoaderRoute: typeof DemoRivalKRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/sheaf-admm-mnist': {
      id: '/demo/sheaf-admm-mnist'
      path: '/demo/sheaf-admm-mnist'
      fullPath: '/demo/sheaf-admm-mnist'
      preLoaderRoute: typeof DemoSheafAdmmMnistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/two-moon': {
      id: '/demo/two-moon'
      path: '/demo/two-moon'
      fullPath: '/demo/two-moon'
      preLoaderRoute: typeof DemoTwoMoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos/': {
      id: '/demos/'
      path: '/demos'
      fullPath: '/demos/'
      preLoaderRoute: typeof DemosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos/$slug': {
      id: '/demos/$slug'
      path: '/demos/$slug'
      fullPath: '/demos/$slug'
      preLoaderRoute: typeof DemosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoAdditionGrokkingRoute: DemoAdditionGrokkingRoute,
  DemoDamTestRoute: DemoDamTestRoute,
  DemoDenseAssociativeMemoryRoute: DemoDenseAssociativeMemoryRoute,
  DemoLinearSystemsRoute: DemoLinearSystemsRoute,
  DemoMnistNkClusteringRoute: DemoMnistNkClusteringRoute,
  DemoMnistTrainingRoute: DemoMnistTrainingRoute,
  DemoNeedleRoute: DemoNeedleRoute,
  DemoNkClusteringRoute: DemoNkClusteringRoute,
  DemoOnlineKMeansRoute: DemoOnlineKMeansRoute,
  DemoRivalKRoute: DemoRivalKRoute,
  DemoSheafAdmmMnistRoute: DemoSheafAdmmMnistRoute,
  DemoTwoMoonRoute: DemoTwoMoonRoute,
  DemosSlugRoute: DemosSlugRoute,
  DemoIndexRoute: DemoIndexRoute,
  DemosIndexRoute: DemosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
