/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemosTwoMoonRouteImport } from './routes/demos/two-moon'
import { Route as DemosNkClusteringRouteImport } from './routes/demos/nk-clustering'
import { Route as DemosMnistTrainingRouteImport } from './routes/demos/mnist-training'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemosTwoMoonRoute = DemosTwoMoonRouteImport.update({
  id: '/demos/two-moon',
  path: '/demos/two-moon',
  getParentRoute: () => rootRouteImport,
} as any)
const DemosNkClusteringRoute = DemosNkClusteringRouteImport.update({
  id: '/demos/nk-clustering',
  path: '/demos/nk-clustering',
  getParentRoute: () => rootRouteImport,
} as any)
const DemosMnistTrainingRoute = DemosMnistTrainingRouteImport.update({
  id: '/demos/mnist-training',
  path: '/demos/mnist-training',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demos/mnist-training': typeof DemosMnistTrainingRoute
  '/demos/nk-clustering': typeof DemosNkClusteringRoute
  '/demos/two-moon': typeof DemosTwoMoonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demos/mnist-training': typeof DemosMnistTrainingRoute
  '/demos/nk-clustering': typeof DemosNkClusteringRoute
  '/demos/two-moon': typeof DemosTwoMoonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demos/mnist-training': typeof DemosMnistTrainingRoute
  '/demos/nk-clustering': typeof DemosNkClusteringRoute
  '/demos/two-moon': typeof DemosTwoMoonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demos/mnist-training'
    | '/demos/nk-clustering'
    | '/demos/two-moon'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/demos/mnist-training' | '/demos/nk-clustering' | '/demos/two-moon'
  id:
    | '__root__'
    | '/'
    | '/demos/mnist-training'
    | '/demos/nk-clustering'
    | '/demos/two-moon'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemosMnistTrainingRoute: typeof DemosMnistTrainingRoute
  DemosNkClusteringRoute: typeof DemosNkClusteringRoute
  DemosTwoMoonRoute: typeof DemosTwoMoonRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos/two-moon': {
      id: '/demos/two-moon'
      path: '/demos/two-moon'
      fullPath: '/demos/two-moon'
      preLoaderRoute: typeof DemosTwoMoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos/nk-clustering': {
      id: '/demos/nk-clustering'
      path: '/demos/nk-clustering'
      fullPath: '/demos/nk-clustering'
      preLoaderRoute: typeof DemosNkClusteringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos/mnist-training': {
      id: '/demos/mnist-training'
      path: '/demos/mnist-training'
      fullPath: '/demos/mnist-training'
      preLoaderRoute: typeof DemosMnistTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemosMnistTrainingRoute: DemosMnistTrainingRoute,
  DemosNkClusteringRoute: DemosNkClusteringRoute,
  DemosTwoMoonRoute: DemosTwoMoonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
